summary: A global sensitivity analysis is conducted with correlated random variables
  using the SimCenterUQ engine for sensitivity analysis.
archive: $SIMCENTER_DEV
archive_location: quoFEM/examples/qfem-0009
collection-title: Simple Truss
id: qfem-0009
medium: quoFEM
system: quoFEM
title: Global sensitivity with SimCenterUQ
type: book
