summary: This example illustrates how quoFEM interacts with the FEAP engine for finite
  element analysis. A simple forward propagation procedure is run to estimate the
  first and second central moments of a truss model's response, given the marginal
  distributions of various random parameters.
archive: $SIMCENTER_DEV
archive_location: quoFEM/examples/qfem-0010
collection-title: Simple Truss
id: qfem-0010
medium: quoFEM
programming-language: FEAP
system: quoFEM
title: Forward Propagation - FEAP
type: book
difficulty: 0
