URL: https://github.com/NHERI-SimCenter/quoFEM/tree/master/examples/qfem-0001
summary: This example illustrates how quoFEM interacts with the Tcl interpreter for
  OpenSees. A simple forward propagation procedure is run to estimate the first and
  second central moments of a FE model's response, given the marginal distributions
  of various random parameters.
system: quoFEM
difficulty: 0
